import 'package:crystal_memories/models/level_info.dart';

final levels = [
  const LevelInfo(
    id: 0,
    matrixSize: 2,
    duration: Duration(seconds: 2),
    flickCount: 0,
    coins: 1000,
    space: 20,
    total: 4,
  ),
  const LevelInfo(
    id: 1,
    matrixSize: 3,
    duration: Duration(seconds: 2),
    flickCount: 0,
    coins: 2000,
    space: 12,
    total: 9,
  ),
  const LevelInfo(
    id: 2,
    matrixSize: 4,
    duration: Duration(milliseconds: 1500),
    flickCount: 0,
    coins: 3000,
    space: 9,
    total: 15,
  ),
  const LevelInfo(
    id: 3,
    matrixSize: 5,
    duration: Duration(milliseconds: 1500),
    flickCount: 0,
    coins: 4000,
    space: 7,
    total: 15,
  ),
  const LevelInfo(
    id: 4,
    matrixSize: 5,
    duration: Duration(seconds: 1),
    flickCount: 0,
    coins: 5000,
    space: 7,
    total: 15,
  ),
  const LevelInfo(
    id: 5,
    matrixSize: 6,
    duration: Duration(seconds: 1),
    flickCount: 0,
    coins: 6000,
    space: 6,
    total: 15,
  ),
  const LevelInfo(
    id: 6,
    matrixSize: 6,
    duration: Duration(milliseconds: 750),
    flickCount: 0,
    coins: 7000,
    space: 6,
    total: 15,
  ),
  const LevelInfo(
    id: 7,
    matrixSize: 6,
    duration: Duration(milliseconds: 750),
    flickCount: 2,
    coins: 8000,
    space: 6,
    total: 15,
  ),
  const LevelInfo(
    id: 8,
    matrixSize: 7,
    duration: Duration(milliseconds: 750),
    flickCount: 2,
    coins: 9000,
    space: 5,
    total: 15,
  ),
  const LevelInfo(
    id: 9,
    matrixSize: 7,
    duration: Duration(milliseconds: 750),
    flickCount: 2,
    coins: 10000,
    space: 5,
    total: 15,
  ),
];
